#!/usr/bin/php -q
<?php

chdir(dirname($argv[0]));

require "../vendor/autoload.php";

unlink("translate.js");
$file = file_get_contents("translate.php");
$translator = new Aftermarketpl\PHP2JS\Translator($file);
$f = fopen("translate.js", "w");
fputs($f, $translator->getResult());
fclose($f);

?>